### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by leporel** [nscuro/traefik-plugin-geoblock#26]
`allowedCountries` does not relate to allow logic, allowing only works when i set `allowPrivate: true`

I run traefik in docker container on macvlan (192.168.6.0\24) network on my server (192.168.0.2) behind router (192.168.0.1\24)

logs 
```
geoblock@file: [XXX GET /player/] blocked request from 192.168.0.1" module=github.com/nscuro/traefik-plugin-geoblock plugin=plugin-geoblock
```

**Comment by nscuro** [comment]
Hi @leporel. 

As you can see in the log entry, the client connecting to your traefik instance is your router (`192.168.0.1`). 
That is a private IP address, which cannot be correlated to a country. That's why you need `allowPrivate: true`.

In fact, with that setup, geoblocking based on IPs is not possible.

**Comment by leporel** [comment]
thx for replay 
I realized my problem, NAT on the router was set up in such a way that it replaced the real IP
